# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_master', '0004_monitorproblem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitornotifydetail',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitornotifydetail',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='monitorproblem',
            name='type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('NETWORK', 'NETWORK'), ('DISK', 'DISK'), ('MEMORY', 'MEMORY')], max_length=15, verbose_name='\u7c7b\u578b'),
        ),
    ]
