# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_master', '0005_auto_20180412_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritem',
            name='type',
            field=models.CharField(choices=[('cpu', 'cpu'), ('disk', 'disk'), ('memory', 'memory'), ('network', 'network')], default='disk', max_length=20, verbose_name='\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
