# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_master', '0006_monitoritem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u914d\u7f6e\u540d\u79f0')),
                ('value', models.CharField(max_length=255, verbose_name='\u914d\u7f6e\u503c')),
            ],
        ),
    ]
