# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_master', '0007_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorNotifyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('weChat', 'weChat')], max_length=10, verbose_name='\u901a\u77e5\u7c7b\u578b')),
                ('account', models.CharField(max_length=255, verbose_name='\u63a5\u6536\u5e10\u53f7')),
                ('hosts', models.ManyToManyField(to='monitor_master.MonitorHost', verbose_name='\u4e8b\u4ef6\u4e3b\u673a')),
            ],
        ),
    ]
