# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180321_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformhosts',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformhosts',
            name='status',
            field=models.CharField(default='down', max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
