# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180323_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformhosts',
            name='disk',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u78c1\u76d8'),
        ),
        migrations.AlterField(
            model_name='platformhosts',
            name='address',
            field=models.CharField(max_length=32, unique=True, verbose_name='IP\u5730\u5740'),
        ),
    ]
