# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180331_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortemplate',
            name='items',
            field=models.CharField(default='cpu,memory,disk,network', max_length=255, verbose_name='\u76d1\u63a7\u9879'),
            preserve_default=False,
        ),
    ]
