# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_monitortemplate_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorhost',
            name='port',
            field=models.CharField(default=7000, max_length=32, unique=True, verbose_name='\u7aef\u53e3'),
            preserve_default=False,
        ),
    ]
