# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_monitorhost_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10, verbose_name='\u901a\u77e5\u65b9\u5f0f')),
                ('theme', models.CharField(max_length=32, verbose_name='\u4e3b\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('send_to', models.CharField(max_length=64, verbose_name='\u63a5\u6536\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorNotifyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4')),
                ('address', models.CharField(max_length=32, verbose_name='\u4e3b\u673a')),
                ('level', models.CharField(max_length=16, verbose_name='\u7ea7\u522b')),
                ('status', models.CharField(default='unconfirmed', max_length=16, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.AddField(
            model_name='monitortemplate',
            name='interval',
            field=models.CharField(default='60s', max_length=5, verbose_name='\u76d1\u63a7\u9891\u7387'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorhost',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='monitorhost',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.MonitorTemplate', verbose_name='\u6a21\u7248'),
        ),
        migrations.AlterField(
            model_name='platformcomponent',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.platformhosts', verbose_name='\u4e3b\u673aIP'),
        ),
    ]
