# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180401_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorhost',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.MonitorNotifyPolicy', verbose_name='\u62a5\u8b66\u7b56\u7565'),
        ),
        migrations.AddField(
            model_name='monitornotify',
            name='status',
            field=models.CharField(default='send', max_length=10, verbose_name='\u53d1\u9001\u72b6\u6001'),
        ),
    ]
