# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180401_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitorNotify',
            new_name='MonitorNotifydetail',
        ),
        migrations.RemoveField(
            model_name='monitorhost',
            name='policy',
        ),
        migrations.AddField(
            model_name='monitornotifypolicy',
            name='danger_threshold',
            field=models.CharField(default='t', max_length=255, verbose_name='danger\u9600\u503c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitornotifypolicy',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitornotifypolicy',
            name='promote',
            field=models.CharField(default='test', max_length=255, verbose_name='\u5347\u7ea7\u9600\u503c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitornotifypolicy',
            name='warning_threshold',
            field=models.CharField(default='test', max_length=255, verbose_name='warning\u9600\u503c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitortemplate',
            name='policy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u544a\u8b66\u7b56\u7565'),
        ),
    ]
